# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        password: ${{secrets.VPS_PASSWORD}}
        host: ${{secrets.VPS_IP}}
        username: ubuntu-1036029
        port: 22
        script: |
          cd /home/ubuntu-1036029/test
          git pull
          npm install
          node index.js